version: "2"
services:
  www:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      WEB_DOCUMENT_ROOT: "/var/www/html/public"
      DEBUG: ${DEBUG}
      APP_ENV: ${APP_ENV}